# 워크플로우 이름
name: Run Notice Scraper

# 이 워크플로우를 언제 실행할지 정의
on:
  # 30분마다 자동으로 실행 (cron 스케줄 문법)
  schedule:
    - cron: '*/5 * * * *'
  # Actions 탭에서 수동으로 실행할 수 있도록 버튼 추가
  workflow_dispatch:

# 실제 실행될 작업 내용
jobs:
  build:
    # 실행될 환경 (우분투 최신 버전)
    runs-on: ubuntu-latest

    steps:
      # 1. 내 저장소의 코드를 서버로 가져옴
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 파이썬 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # 원하는 파이썬 버전

      # 3. 필요한 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 파이썬 스크립트 실행
      - name: Run Python Scraper
        # GitHub Secrets에 저장한 비밀 키를 환경변수로 주입
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        run: python scraper.py
