# 워크플로우 이름
name: Run Notice Scraper (DEBUG MODE)

# 이 워크플로우를 언제 실행할지 정의
on:
  # Actions 탭에서 수동으로 실행할 수 있도록 버튼 추가
  workflow_dispatch:

# 실제 실행될 작업 내용
jobs:
  debug-job:
    # 실행될 환경 (우분투 최신 버전)
    runs-on: ubuntu-latest

    steps:
      # 1. 내 저장소의 코드를 서버로 가져옴
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- 디버깅 단계 추가 ---
      - name: 1. 현재 작업 위치 확인 (Print Working Directory)
        run: pwd

      - name: 2. 전체 파일 및 폴더 구조 확인 (List all files recursively)
        run: ls -R
      # --- 디버깅 단계 끝 ---

      # 3. 파이썬 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4. 필요한 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. 파이썬 스크립트 실행
      - name: Run Python Scraper
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        run: python scraper.py